# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20171130_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_num',
            field=models.IntegerField(default=0, verbose_name='商品数量'),
        ),
    ]
