# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0002_auto_20171130_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userleavemessage',
            name='message_type',
            field=models.IntegerField(choices=[(1, '留言'), (2, '投诉'), (3, '询问'), (4, '售后'), (5, '求购')], default=1, max_length=10, verbose_name='留言类型'),
        ),
    ]
