# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 12:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20171205_1223'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_operation', '0004_auto_20171205_1223'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfav',
            unique_together=set([('user', 'goods')]),
        ),
    ]
