# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 23:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0005_auto_20171215_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='province',
            field=models.CharField(default='', max_length=100, verbose_name='省份'),
        ),
        migrations.AlterField(
            model_name='userfav',
            name='goods',
            field=models.ForeignKey(help_text='商品Id', on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='userleavemessage',
            name='file',
            field=models.FileField(help_text='上传的文件', upload_to='message/images', verbose_name='上传的文件'),
        ),
        migrations.AlterField(
            model_name='userleavemessage',
            name='message_type',
            field=models.IntegerField(choices=[(1, '留言'), (2, '投诉'), (3, '询问'), (4, '售后'), (5, '求购')], default=1, help_text=((1, '留言'), (2, '投诉'), (3, '询问'), (4, '售后'), (5, '求购')), verbose_name='留言类型'),
        ),
        migrations.AlterUniqueTogether(
            name='userfav',
            unique_together=set([]),
        ),
    ]
